name: Build and Upload LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: ./thesis/NIR/
          root_file: ./thesis/NIR/main.tex
          
      - run: mkdir -p ./thesis/NIR/
      - run: echo hello > ./thesis/NIR/main.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /thesis/NIR/main.pdf

          
